id: P7FD26C6D
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA1KG4301
  instance_id: http://purl.bdrc.io/resource/IE1KG4301
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - རྒྱལ་བ་ལོ་རས་པ་གྲགས་པ་དབང་ཕྱུག་མཆོག་གི་རྣམ་ཐར།
  alt_title: {}
  author: None
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    8c89a6078e124b199e551983270be72d:
      title: པོད ༡་རྒྱལ་བ་ལོ་རས་པ་གྲགས་པ་དབང་ཕྱུག་མཆོག་གི་རྣམ་ཐར
      volume_number: 1
      base_file: UT1KG4301_I1KG4424_0000.txt
      reference: http://purl.bdrc.io/resource/VL4633AD1A1B90CAD1
      image_group: I1KG4424
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/MW1KG4301
  - http://purl.bdrc.io/resource/W1KG4301
  ocr_software: Namsel
created_at: '2021-12-22T10:40:49.561421'
last_modified_at: '2021-12-22T10:40:49.561427'
